### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#1]
To integrate into existing app, top of the page needs to be similar if not identical:

![Screenshot from 2021-07-07 09-43-58](https://user-images.githubusercontent.com/20199778/124719938-ef732d00-df07-11eb-8513-a2f3df70ba84.png)

Logo + menus (at least same accessible functions)

The menus are build here: https://github.com/ecotaxa/ecotaxa_dev/blob/2a1696f030edd88792c084244263f0abb5f92100/appli/project/main.py#L287

Main constraint: no <table> just <div>

Possible inspiration: https://github.com/ecotaxa/ecotaxa_dev/blob/master/appli/static/cpics_import.html

**Comment by LaurentReese** [comment]
PrimeVue usage is advised

**Comment by LaurentReese** [comment]
Make the banner generally smaller (its title as well).

**Comment by LaurentReese** [comment]
**dev notes :**
Regarding points 6 and 7 of https://github.com/ecotaxa/ecotaxa_front/issues/1#issuecomment-876180338
6) "Admin Screen" => only if admin or admin user rights
7) "Task Manager" => only if admin or admin user rights
See **ecotaxa_dev/appli/main.py** :
" if user_can_administrate or user_can_administrate_users:
        g.menu.append(("", "SEP"))
        g.menu.append(("/admin/", "Admin Screen"))
        g.menu.append(("/Task/listall", "Task Manager"))
"
+
 with ApiClient(UsersApi, request) as api:
        try:
            user: UserModelWithRights = api.show_current_user_users_me_get()
