### ISSUE TITLE
Changer la suppression (delete) de projets ou d'objets

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#108]
Devrait être un gros bouton rouge (avec une confirmation explicite) en bas de la page "Project settings" et devrait automatiquement entrainer la suppression de tous les objets associés. Cela simplifierait le menu "Delete objects".

**Comment by picheral** [comment]
Message indiquant la probable durée de l'action. Trop couteux à mettre en tâche asynchrone d'autant plus que le problème semble peu fréquent depuis que l'app. fonctionne bien.

**Comment by jiho** [comment]
Le pb n'est pas la durée, c'est l'UI/UX.

En résumé:

1. Menu `Filtered > Delete objects` donne accès à une page avec:

"You are about to delete 345,485 objects.
[Delete those objects] [Cancel]"

Delete est rouge, Cancel est bleu.

Le nombre est le résultat du filtre.

2. Menu `Project > Delete objects or project` est supprimé

3. Dans la page `Edit project settings`, tout en bas, un bouton rouge est ajouté avec [Delete project] qui revoie vers une page avec:

"You are about to delete 1,456,355 objects and completely remove project `Nom du projet`.
[I am sure, delete this project and all of its data] [Cancel]"

Delete est rouge, Cancel est bleu.

Le nombre est le nombre total d'objets dans le projet.

**Comment by grololo06** [comment]
A partir de la 2.4.2 ça ira beaucoup + vite, ceci dit un petit sablier ou une barre de progression (sans task) ne ferait pas de mal.

**Comment by jiho** [comment]
J'avais oublié la spécification ci-dessus mais j'ai refait ~ la même dans #393 donc on va dire que c'est un signe que c'est un choix logique (dans ma tête au moins).

À implémenter.

**Comment by grololo06** [comment]
Vu l'importance des dégâts potentiels, je suggère, dans une page de confirmation, de forcer l'utlisateur à taper le nombre d'objets qui vont disparaître. Interdire le copier/coller dans ce champ.
