### ISSUE TITLE
Interface description for various taxonomy remappings

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#138]
Currently, it is possible to remap categories as part of the the classification interface. It comes at the end and could actually be a completely separate tool. As a separate tool, it would have broader uses (cf discussion with Rainer regarding the classification into clusters). It seems that it would be a better idea to make it separate in the end.

**Comment by picheral** [comment]
Préciser l’outil pour la V2… Limité à une catégorie ou possibilité copier-coller texte mapping comme import ?
Ce sera donc un outil de la V2

**Comment by jiho** [comment]
Le plus simple serait de reprendre exactement l'UI actuellement à la fin de la pred auto:
- une colonne avec les noms actuels
- une colonne avec des select box avec les noms futurs
- par défaut les noms actuels sont reportés dans les noms futurs = pas de de changement
- si on change vers un autre nom, ça fait un remapping
- si on change vers rien ça enlève le nom =  ça met les objets à "None" (avec un warning). Il y a parfois besoin de repartir à 0 sur certaines classes qui sont en bordel. Ça ouvrirait cette possibilité (actuellement impossible).

**Comment by grololo06** [comment]
To dispatch per function, "generic" cannot apply here as the data sets and behavior is different each time.

**Comment by jiho** [comment]
The UI should be generic. The code to implement the remapping will indeed be different for each use case. Do you want a separate issue per use case?

**Comment by grololo06** [comment]
Well, I don't 'want', it's simply that cross-function developments don't fit well in the project model with per-function labels. Maybe the title itself is misleading.
