### ISSUE TITLE
Setting "Use Deep Learning features" is not remembered between predictions

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#148]
Everything is in the title

**Comment by grololo06** [comment]
Not really a bug. Specs are needed, should the setting be remembered per project or user or project+user or ???

**Comment by jiho** [comment]
Same as the rest of the automatic prediction settings, which is per project I think (or it should at least). The bug is in the fact that the ticking of the box at the last step of the automatic classif settings is not remembered while the list of fields used is for example.
