### ISSUE TITLE
Move/duplicate page changing buttons in classification page

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#157]
Page changing buttons should also be at the top or appear on hover at the bottom of the browser window (css: fixed) so that it is possible to change page without having to scroll down a large page (of 1000 objects).

via Rainer.

**Comment by grololo06** [comment]
With usability survey group, it seems that we are heading towards a fixed page bottom, with the page navigation buttons inside.

**Comment by picheral** [comment]
OK for a bottom panel.

**Comment by grololo06** [comment]
30/09/2021: JO is OK with "always visible navigation" in the bottom.
