### ISSUE TITLE
Monitor who is currently working on a project

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#166]
And signal it somewhere in the UI (top corner or something).

This is a very important request from users who do not understand why some images are "disappearing" from their projects when viewing only non-validated ones => someone else is also classifying the project.

**Comment by picheral** [comment]
S'il est difficile de savoir l'activité réelle de quelqu'un sur un projet. Il peut travailler 15 min ou plus à trier sans valider... Il y aura dans ce cas un retard important !
Une solution peu couteuse est la page "about" qui affiche à la demande des statistiques recalculées sur le projet.

**Comment by picheral** [comment]
Afficher dans le topper les deux derniers utilisateurs ayant trié depuis moins de 30 min et indiquer le temps.
Se fait à chaque refresh de la page Classif

**Comment by picheral** [comment]
#382
