### ISSUE TITLE
Améliorer et homogénéiser le tableau de listing des projets

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#182]
La liste est un tableau, dans lequel toutes les colonnes sont triables et filtrables en ajax (e.g. > à pour les nombres, fuzzy matching pour le texte, voir #183)

Dans tous, avoir les colonnes suivantes:
- Action: select, request, coche, etc.
- Project Id 
 - Info: Titre [eye] qui étant un lien vers la page projet, qui s'ouvre dans un nouvel onglet; Ajouter une zone collapsable qui contient (NB: certaines choses ne seront possibles qu'une fois que les stats pour la page About project seront calculées):
    - liste des tous les project manager avec mailto
    - project description
    - Date of last update: 2017-09-13 (si facile/dispo)
    - Categories (n=90): Copepoda (3452), Calanoida (546), … liste complète
    - Features (n=43): mean, area, … liste complète
    - Deep-learning network: UVP detailed
    
- Instrument
- My status: Annotator/Viewer/Manager/No access
- Project status: Annotate/Explore/...
- Nb objects
- % valid (% classif est supprimé)
- Nb categories

 Ceci est donc vrai pour tous les outils suivants
- http://ecotaxa.obs-vlfr.fr/prj/ et dans http://ecotaxa.obs-vlfr.fr/prjothers/
- http://ecotaxa.obs-vlfr.fr/prj/merge/ (qui deviendra un outil séparé #188 )
- "Train and Predict identifications"

Pour merge et train, ajouter:
- Nb of matching features 
- CNN network

**Comment by picheral** [comment]
Utiliser : https://datatables.net/examples/basic_init/zero_configuration.html
Version AJAX, 
Pagination paramétrable
Possibilité export Excel et CSV

**Comment by picheral** [comment]
Doit aussi être utilisable, tout comme les filtres pour OTHER PROJECTS...

**Comment by jiho** [comment]
De plus, il serait utile d'avoir:
- la possibilité d'épingler un projet
- une détection `n` projets dans lesquels l'utilisateur a fait une annotation récente ( #4 )

Ces projets seraient mis en tête de liste par défaut (pinned, recent, rest) et mis en valeur (pinned = icone pin, fond jaune; recent = icone montre, fond bleu clair). Si l'utilisateur fait un tri différent, ils seraient triés avec le reste mais garderaient leur mise en valeur.

Ces projets pourraient également être mis à disposition dans le menu en haut à droite (action)

**Comment by grololo06** [comment]
Il faudrait lister les cas typiques d'utilisation, car trop d'information peut gêner les gens qui ont des besoins basiques.

**Comment by LaurentReese** [comment]
Cette issue est très très riche (avec des liens sur d'autres pages/fonctionnalités), il faut l'organiser en priorités (sinon on va se perdre à vouloir tout faire - tout mal).
Après une première discussion le 16/6/2021 avec Laurent S, je propose les priorités suivantes :

**Comment by grololo06** [comment]
#669 adds a requirement "filter on the project that current user manages", so this should be part of the table component interface.

**Comment by LaurentReese** [comment]
liens potentiellement utiles :

**Comment by grololo06** [comment]
On va faire du server-side filtering & ordering. Pas **toutes** les colonnes sinon trop complexe.

**Comment by grololo06** [comment]
- Explication pour "Nb of matching features".

En entrée (commun à tous les projets de la liste): une prop sous la forme d'une liste de string e.g. ['area', 'circ', toto']

Chaque projet possède des colonnes libres, p.e.:
![Capture d’écran de 2021-06-24 09-54-46](https://user-images.githubusercontent.com/20199778/123225150-b6cc6000-d4d2-11eb-891c-9fdb09a50bc5.png)

En sortie, le nombre de string communes entre la prop et les entrées dans obj_free_cols

Dans l'exemple il n'y a pas 'circ' ni 'toto', donc à afficher c'est "1"

**Comment by grololo06** [comment]
Merge link is https://ecotaxa.obs-vlfr.fr/prj/merge/xxxx with xxxx being the target project.

**Comment by LaurentReese** [comment]
A collection can now be created :
Select “Projects I’m in”, select “For managing”, click “Run Query”, select (in left column) one or several projects, then the “Make a collection” button appear, click it, create a collection.

**Comment by LaurentReese** [comment]
Suggestions from Amanda :
- Rename "Name" column into : "Contact Name" : ==> OK
- Rename "User status" column into : "Your status" : ==> OK
- Rename "Status" column into : "Project status" :  ==> OK
- Sort immediately and automatically by Instrument, move this Instrument column (completely) to the left : ==> to be discussed (Marc, JO ...)

**Comment by LaurentReese** [comment]
Ask JO and Marc (From Laetitia : on s'est dit aussi que le "Projects I'm in" et "For managing" est pareil pour un manager).
Donc : faut-il tester que le user est un manager et simplifier la UI dans ce cas ?
