### ISSUE TITLE
Admin: Ajout d'informations dans l'administration des utilisateurs

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#193]
La page est accessible à l'application manager et au user manager.

Actuellement il y a un tableau automatique. Il faudrai un tableau avec nom, email, organisation, active, role + nb d'annotations manuelles, date dernière annotation.

Tableau triable et filtrable sur n'importe quelle colonne.

Editer un utilisateur doit permettre de changer:
- nom
- email
- mot de passe
- role
- active. Passer un utilisateur inactif doit:
    - purger ses droits sur tous les projets
    - le rendre invisible dans tous les outils de sélection des utilisateurs (ajout à un projet cf #3 )

**Comment by picheral** [comment]
Ajouter la date d'enregistrement de l'utilisateur dans l'application

**Comment by picheral** [comment]
Page USERS Stats à créer ! 
La correction des problèmes de tri de la page existante est couteuse:

- Ne laisser le bouton de tri que sur le champ qui fonctionne.

**Comment by picheral** [comment]
Composant Datatable.

**Comment by picheral** [comment]
Un utilisateur INACTIF ne peut plus se logger (vérifier).
Il est intéressant de le conserver ainsi que ses droits dans les projets.
En fonction des listes utilisateurs présentes dans l'application, afficher listes AVEC/SANS inactifs.

**Comment by picheral** [comment]
Pour la version 1.6, on ne gère que la question ACTIF/INACTIF : 
- vérifier qu'il ne peut plus se logger

La purge se fera plus tard...

**Comment by laurent-n** [comment]
déja fait : user inactif ne peux pas se logguer , les inactifs ne sont pas dans les listes basées sur select2 (avec recherche)
