### ISSUE TITLE
Object aka image component

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#2]
What will be needed for sure and is not a standard Prime component is:
![Screenshot from 2021-07-07 10-23-18](https://user-images.githubusercontent.com/20199778/124725850-81316900-df0d-11eb-8113-53cd39ce2062.png)

Which is, for now, hand made in python in https://github.com/ecotaxa/ecotaxa_dev/blob/2a1696f030edd88792c084244263f0abb5f92100/appli/project/main.py#L621

E.g., from prototype:
![Screenshot from 2021-07-07 10-27-37](https://user-images.githubusercontent.com/20199778/124726444-0b79cd00-df0e-11eb-9ff1-0e325e71e240.png)

The goal is to to have a component for future Manual Classification page.

PS: No `<table>`

**Comment by grololo06** [comment]
While using the component to come, we should end up in something like:

<EcoTaxaObject id="455555" />

**Comment by LaurentReese** [comment]
Use ObjectsApi, Get Object Set function (ObjectsApi::getObjectSetObjectSetProjectIdQueryPost())

potential fields to specify:

**Comment by LaurentReese** [comment]
Correspondance between fields and labels:
obj.orig_id <==> Image Name
obj.classif_auto_score <==> Score
obj.classif_when <==> Validation date
obj.random_value <==> Random

**Comment by LaurentReese** [comment]
**Various comments after discussion between Laurent S and me :**
1) Loops on project, projects, collections... in order to get their vignettes ID and properties are done outside and before calling the VignetteGeneric component.
2) The vignette category is in bold and centered.
3) Contrary to other generic components, the VignetteGeneric component does only display, no other treatment (especially no API calls, which are performed outside and before calling the VignetteGeneric component => see point 1).
4) Prototype of this component is :
```
<VignetteGeneric
      vignetteName="2446/9844.jpg"
      category="Salpida"
      Score=0.93
      feret=614
      major=524
/>
Or 
<VignetteGeneric
      vignetteName="2446/9844.jpg"
      category="Salpida"
      features="Score:0.93;feret:614;major:524"
/>
```
Except the category that may be changed, all the other fields are "consts"

**Comment by LaurentReese** [comment]
When the category includes a '<', the display is special :
![image](https://user-images.githubusercontent.com/74904892/132829410-69fdb489-5489-4372-a8f0-fa4fca6212b9.png)
Inspire from https://github.com/ecotaxa/ecotaxa_dev/blob/eb209ae1888a0437bd704c8c050c2d3d08807b4b/appli/project/main.py#L830

When the category name is long, a special cut-off must be computed :
![image](https://user-images.githubusercontent.com/74904892/132830075-ca7ba3f6-edac-4237-bfd5-96a776259bbc.png)
Inspire from https://github.com/ecotaxa/ecotaxa_dev/blob/eb209ae1888a0437bd704c8c050c2d3d08807b4b/appli/project/main.py#L349

There are unselected and selected states to handle, like:
![image](https://user-images.githubusercontent.com/74904892/132830301-0843d298-f0c8-4f46-a281-aaa74ece2eaf.png)
and
![image](https://user-images.githubusercontent.com/74904892/132830422-8d4d7948-ee38-411c-84ab-76e6e177e05a.png)

**Comment by LaurentReese** [comment]
TODO : drag and drop behavior to describe

**Comment by LaurentReese** [comment]
Mistake : DO NOT take into account last 2 messages (494d604 and afce06c) : bad issue number reference
