### ISSUE TITLE
Filtrer par BARCODE dans les samples

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#206]
Définir le champ Barcode comme champ normalisé => comme instrument => modifier la doc de la page importation des données.
**Créer un filtre spécifique.**
A terme API permettant la récupération des données par application extérieure.

**Comment by picheral** [comment]
SAMPLE_barcode + retrofit pour ré-initialiser + trt à l'import comme colonne standardisé

**Comment by grololo06** [comment]
I faudrait un exemple pour illustrer, également une explication de 'rétrofit'.

**Comment by jiho** [comment]
1. ajouter un champ `barcode` dans la table `samples`
2. pour tous les projets qui ont `barcode` dans `mappingsample`, copier le contenu du champ correspondant dans le nouveau champ `barcode` et l'effacer du mapping
3. à l'import, détecter `sample_barcode` en plus de `sample_id` et remplir le champ `barcode`

**Comment by jiho** [comment]
Il n'est pas forcément nécessaire de passer le champ en dur pour faire une requête dessus.

**Comment by jiho** [comment]
Une UI possible serait d'utiliser le filtre sample soit en terme d'ID soit de barcode, avec un switch:

<img width="245" alt="Screenshot 2021-02-17 at 17 18 13" src="https://user-images.githubusercontent.com/18445/108233550-31135f00-7144-11eb-9cac-4ab141ed35a5.png">
