### ISSUE TITLE
IMPORTATION : vérifications des TSV en cours d'import par rapport aux imports précédents

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#223]
Il faut renforcer les taches d'importation par des tests préalables permettant d'éviter un abandon sur erreur lorsqu'on lance de gros imports.

- AJOUTER UN WARNING en DEBUT de test des TSV pour demander si on veut continuer si TSV différents. Gérer les cas:
* Cas des fichiers qui ne débutent pas par "ecotaxa"
 * Indiquer par un résumé simple que les tables TSV importées sont parfaitement identiques (ou pas) à l’état actuel de la table (même colonnes ou pas).
* Si au moins une colonne manque ou est supplémentaire par rapport à l’état actuel de la table, mettre un message et demander explicitement s’il faut continuer ou abandonner.
* Mettre une alerte si on passe les 500 car ça fait planter par la suite.

Si erreurs non détectées lors de ce test préliminaire: 
* Fournir la liste de ceux qui n'ont pas pu s'importer afin de faciliter la recherche du problème. Coder éventuellement certains cas comme un fichier image manquant ou illisible.

**Comment by grololo06** [comment]
A part l'alerte sur les 500 colonnes, qui sera en 2.3, je ne comprends pas avec certitude de quoi il s'agit. 
Je propose d'ouvrir autant d'Issues que de cas à traiter, avec pour chacun:
- Description de la situation rencontrée
- Comportement actuel
- Comportement attendu

**Comment by grololo06** [comment]
Sur premier import (0 existant) OK
Sur les suivants, vérifier si les nouvelles colonnes libres sont != des TSV en cours d'import, et selon, afficher warning/erreur.

**Comment by grololo06** [comment]
Par rapport à la version actuelle, le gros delta est la présence de warnings avant de lancer l'importation, même si celle-ci est possible. L'issue me semble cependant pertinente .
