### ISSUE TITLE
Message alerte dans TOPPER

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#236]
Affichage des alertes dans le bandeau haut quand on est cours de travail ? Possibilité d'effacer dès que c'est vu)
Le message de l’accueil ajouté à cette version.

**Comment by picheral** [comment]
Utilise un message différent de celui de l'accueil.

**Comment by picheral** [comment]
Permettrait de prévenir de la maintenance... ou de diffuser des informations aux utilisateurs.

**Comment by grololo06** [comment]
OK donc "alerte" = message d'administration e.g "Ecotaxa will be unavailable XXXX"

**Comment by grololo06** [comment]
Linked with #666, as of today the home message is a big block of HTML, not split in alert/ordinary welcome.
