### ISSUE TITLE
Change layout of pagination on classification page

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#252]
Currently

```
Page 2/47
[<][1][23][45][47][>]
```

Proposed

```
[<Prev][Next>] Page 2/47 [1][23][45][47]
```

With larger buttons.

The goal it to have the Prev and Next buttons stay at the same place on all pages, which makes reaching them easier.

**Comment by grololo06** [comment]
Current proposal in usability survey/study:
![image](https://user-images.githubusercontent.com/20199778/135239849-8839701d-f8d3-471d-b80a-e6c45491d7dc.png)
