### ISSUE TITLE
Réduire logo dans le header

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#268]
Le logo pourrait être réduit à jute le "E" dans toutes les pages sauf les pages de garde (http://ecotaxa.obs-vlfr.fr et http://ecotaxa.obs-vlfr.fr/part/)

![screen shot 2018-11-12 at 16 35 42](https://user-images.githubusercontent.com/18445/48357539-2500e300-e699-11e8-92ab-30575928d751.png)

**Comment by grololo06** [comment]
Si on avoir un graphiste pour faire un beau logo c'est pas mal aussi.

**Comment by bea777515** [comment]
Réduit , s'affiche dans les petites résolutions .
