### ISSUE TITLE
Scaling is not homogeneous on a single page

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#301]
Example:

![screenshot 2019-03-04 at 11 02 43](https://user-images.githubusercontent.com/18445/53726068-811c8c80-3e6d-11e9-9411-ba4d4444e5d5.png)

The three scale bars are all 1mm and should be exactly the same size. They are not. The initial specifications were "thumbnails are displayed at a fixed proportion of the original thumbnail size". This is paramount to get a sense of scale among organisms.

**Comment by picheral** [comment]
Probablement du à la mise à l'echelle du label de la catégorie taxo.

**Comment by grololo06** [comment]
Hi,
On my dev. environment have this which looks OK at 100% zoom

![Capture d’écran de 2019-11-07 09-33-08](https://user-images.githubusercontent.com/20199778/68372790-d5d17f00-0141-11ea-9b91-480bcd1b1ae7.png)

But indeed when zooming 50% I get the below which is incorrect:

![Capture d’écran de 2019-11-07 09-36-40](https://user-images.githubusercontent.com/20199778/68372976-26e17300-0142-11ea-9f4f-1ff04862eeb2.png)

So the issue looks somehow related with the zoom level.

Can you confirm?

Thanks.

**Comment by grololo06** [comment]
OK after a bit of hacking I get this:

![Capture d’écran de 2019-11-07 10-16-20](https://user-images.githubusercontent.com/20199778/68375736-ae7db080-0147-11ea-9acc-dbcffc4f7877.png)

In which the scale bar is identical, BUT the 2 smaller Copepoda on the left are _really_ small, so probably unusable for identification.
There is a piece of code preventing images from being scaled down below 75px. So it results in kind of image-specific larger zoom factor, hence the visible inconsistency.

Solutions:
- Let very small images be displayed (cheap)
- Ignore exact scaling required by user and apply the nearest consistent one. E.g. if "40%" is required but we see that below "60%" we would have distortion, then apply 60% silently. It's more expensive as it needs a small refactoring of the layout algorithm.
- Same as previous but somehow give feedback to the user (e.g. a message "40% not possible, applying 60%")
- Same as previous but also prevent completely the invalid options from being available to the user. E.g. if there is a gigantic picture is in a displayed set then no zoom at all would be possible.

**Comment by grololo06** [comment]
Sensitive area, but shall we fix and if yes, which option?

**Comment by picheral** [comment]
A discuter avec les opérateurs de la PIQv... Je ne suis personnellement pas gêné par le comportement actuel. On peut ajouter un warning lorsque la page est affichée avec un zoom ne permettant pas l’homogénéité des barres d'échelle.
