### ISSUE TITLE
Shrink too large images during import

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#330]
EcoTaxa currently contains
- .gifs that are > 30MB each, which take a huge amount of space for little value. Should error out.
- .png/.jpg that are >10MB each, which means they are very large (much larger than the display size of a monitor). Should be rescaled to a maximum of 4096px (4K resolution), or more reasonably 2048px.

**Comment by grololo06** [comment]
Simple algorithm proposal in pseudo-code:
```
if size of image_file > 10 millions:
  error "Image file too large"
```
Feel free to amend.

**Comment by jiho** [comment]
To be clear, the problem is with the *dimensions* of individual images, not the number of images. EcoTaxa is for looking at images on a screen, maybe zooming a bit, so images larger than what can be displayed are useless. It would rather be:

```
if width x height > 5M:
    warning "Image file larger than 5M pixels, it will be resized to a maximum dimension of 1200px and the larger images will be discarded"
```

The 5M threshold has to be thought about. 1200x1200 is 1.5M pixels. Maybe a 2M threshold is enough.
