### ISSUE TITLE
Purge des données produites par les exportations sur FTP

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#348]
Il est nécessaire de permettre à un utilisateur ayant exporté ses données sur le FTP de pouvoir les purger après récupération.
Il serait aussi souhaitable de mettre en place un mécanisme de purge automatique à l'échéance d'un délais pré-établi et indiqué dans les fenêtres permettant d'exporter vers le FTP.

**Comment by grololo06** [comment]
Les données provenant de tasks d'export, elles doivent disparaître avec lesdites task, c'est-à-dire sur demande de l'utilisateur ou par le "cron" de nettoyage. Il faut avertir l'utilsateur.

**Comment by jiho** [comment]
À revoir avec l'organisation du FTP via IFREMER

**Comment by grololo06** [comment]
On se dirige vers un répertoire perso avec quota, ce qui simplifierait pas mal ce genre de problème de partage.
