### ISSUE TITLE
Create an "About project" page

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#382]
Création d'une page permettant à tout annotateur d'un projet d'obtenir une vision synthétique de l'activité sur le projet.

**Comment by grololo06** [comment]
Comprenant #66

**Comment by jiho** [comment]
In this page, there should be

## General information about the project

= Information similar to the project settings (but not editable)

Title
Description
Comments
License
Available fields at sample, subsample and object level (i.e. the "mappings")
SCN network
_**Extra bonus points**_ for a user-readable description of the last classification settings.

## Users

Contact person with email

List of managers with emails

List of all users (including past ones who might not be associated to the project anymore and whose validations may have been overwritten = in the history table) with the name (link to email), number of annotations (i.e. validation, or set as dubious) and date of last annotation.
_**Extra bonus points**_ to get a dynamic plot of the number of annotation per user and per calendar week.

## Samples

Table of samples with columns giving the nb of objects of each status (validated, dubious, ...).
_**Bonus points**_ for the ability to sort per column.
_**Extra bonus points**_ for the ability to select samples (checkbox) and have a button: [Go sort these samples] that sends to the manual classif page with the selection of samples applied.

## Taxa

Table of taxa in taxonomic hierarchy order with columns for the number of objects per status
_**Bonus points**_ for the ability to sort per column.

NB: + Ability to export these tables in .tsv

**Comment by jiho** [comment]
Accessible the same way as the rest of the manual classif page = to all user when project is "visible", to viewers and up when project is non "visible".

**Comment by picheral** [comment]
Je suis OK avec la spec. Les BONUS sont importants.... et on peut se passer des EXTRA BONUS si nécessaire.

**Comment by LaurentReese** [comment]
Correspondence to "json fields" from fields described by JO:
Title ==> title
Description ==> projtype
Comments ==> comments
License ==> license
Available fields at sample, subsample and object level (i.e. the "mappings") ==> use sample_free_cols, acquisition_free_cols and process_free_cols (to better understand/define)
SCN network ==> cnn_network_id

**Comment by LaurentReese** [comment]
Commentaires de J.O. que j'essaye de numéroter:
1) Je mettrai bien le titre dans le bandeau de titre

2) License = lien vers le texte chez Creative Commons

3) Si ça peut être un badge officiel c'est encore mieux

4) Free fields: la disposition en tableau prend pas mal de place et marche mal en responsive. Je serai pour être un peu plus compact, voire carrément faire just une liste sous format texte

5) Project managers vs users: pourquoi c'est formaté différemment ? Souvent les managers trient aussi donc il faudraient qu'ils soient dans la seconde liste aussi (edited) 

6) Il faudrait une légende pour la partie users. Je suppose que le badge c'est le nombre de classif et la date c'est la date de dernier classif mais c'est pas évident

7) Pour les samples et taxa, il faudrait afficher le nom (orig_id et name) plutôt que l'identifiant numérique

8) Pour la présentation, les nombres sont déjà bien, s'ils pouvaient être colorés en fonction de le statut ce serait mieux. Si ça pouvait être représenté sous forme de "progress bar" ce serait encore encore mieux.
= barre de même longueur, avec les différentes couleurs qui donnent les proportion et les nombres écrits au sein de la barre idéalement

<div class="progress">
  <div class="progress-bar bg-info" role="progressbar" style="width: 10%" >25</div>
  <div class="progress-bar bg-success" role="progressbar" style="width: 30%" >75</div>
  <div class="progress-bar bg-warning" role="progressbar" style="width: 60%" >150</div>
</div>

9) Taxa = pluriel déjà (taxon = singulier)
(donc pas taxaS)

 10)Je mettrai bien le bouton [export in .tsv] au bout de la ligne du titre, aligné à droite si possible. Sinon juste en dessous du titre comme pour samples (mais pas comme pour taxa)

11) Graphiquement, tout est un peu gros, mais ça c'est le style bootstrap par défaut, ça se change derrière

12) Ce qui m'amène à mon dernier point: si cette page pouvait être l'occasion de mettre en place le pipeline pour utiliser bootstrap de façon sémantique et éviter les n <div class="container">, les class="btn btn-primary" etc. ce serait cool

13) Dans le code:
    je vois plein de <p> et de <pre> vides entre chaque section. C'est bizarre
    Il y a un container par section alors que je croyais que container c'était typiquement pour la page ou un gros bout de page et qu'ensuite on faisait des <row>

**Comment by LaurentReese** [comment]
vu avec JO :
- Le point 11 revient (tout est un peu gros), densifier les infos, améliorer le style.
- Voir si on peut mettre les infos dans des composants PrimeVue.
- Les 2 dernières tables "Samples with objects and status" et "Taxa" doivent être des datatable primevue, avec les colonnes triables.
