### ISSUE TITLE
Add a "Recent projects" list

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#4]
In the "Action" menu on the right. The 5 most recent for the currently active user.

**Comment by grololo06** [comment]
Small work left: define "recent". Users can view/manage/annotate in project.

**Comment by jiho** [comment]
5 last projects in which the user made an annotation.

Those should be in the menu on the right and possibly in a separate section in the project selection page, before the complete list.

**Comment by grololo06** [comment]
OK it will be only in the Action menu and record the accessed projects (read/write), because it's easier to implement, understand for users, and I want to have the function even if I never annotate :)

**Comment by grololo06** [comment]
Fixed 4 years 1/2 after, in 2.5.2.

**Comment by jiho** [comment]
🥳
