### ISSUE TITLE
GDPR review of the application

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#427]
https://www.cnil.fr/fr/reglement-europeen-protection-donnees

**Comment by grololo06** [comment]
I wonder if people agreed to have their names in clear, e.g. in classification history.

**Comment by grololo06** [comment]
Dropped user in last classification, still many names & mails are public.

**Comment by jiho** [comment]
Name is mandatory for attribution of the work, the welcome message (at user subscription etc.) should mention this explicitly. Email should be more hidden where possible.
This is more critical as part of the move to IFREMER.
