### ISSUE TITLE
Save named filters per project and share them

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#470]
Currently, within a project, each user can save his/her last set of filters and then apply it back when they come back to the project. At the bottom of the filters section:
![Screenshot 2020-09-17 at 15 33 12](https://user-images.githubusercontent.com/18445/93477276-20dc2700-f8fb-11ea-90f7-dbc1d6abf52c.png)

But:
- one has to remember which filter settings were saved
- those filters are not shareable among users working on the same project

I propose to implement a system where a user can adjust his/her filters within the project, save the current state, give it a name. Then another user of the same project can pick this filter set from a list where the each saved filter is described by its name and, if possible, by a short description of the filtering criteria (similar to what is displayed in bubbles in the top part of the page).
All annotators on the project can edit and delete any filter (including the one of others: annotators work as a team anyway).

This would allow users to say: "have a look at the objects of station 10, below 50 m, captured at night; I have saved it as a filter-set called `weird stuff`".
It would also allow users to switch between contexts while sorting, to preassign samples/taxa/etc. to different levels of priority for sorting (sort all objects in the filter "Priority 1", then move on to filter "Priority 2", etc.).

**Comment by grololo06** [comment]
This looks complex to me, need to poll frequent users.
