### ISSUE TITLE
One to one mapping between EcoPart and EcoTaxa projects

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#482]
Currently, several EcoPart projects can correspond to one EcoTaxa project. This was because we wanted to be able to have homogeneous plankton sorting over several projects. This will be alleviated by collections (#335) and having a 1-1 mapping will be easier for many things.

However, 1-0 (One EcoPart project, no EcoTaxa project) is possible, at least for data from remote UVP6 that do not send images back.

**Comment by grololo06** [comment]
To clarify, e.g. what to do for existing data. It also raises the question on how to reference EcoTaxa project from EcoPart, if there are several EcoTaxa instances. Other point: can we reference a _Collection_ from EcoPart, as #335 is still to clarify.

**Comment by laurent-n** [comment]
Today each EcoPart project contains an optionnal reference to an EcoTaxaProject by it's ProjectID
A second level of mapping it's done at sample level, each ecopart sample are linked to an EcoTaxa sample, this matching is done automaticaly based on the sample name within the project

Has the database will be splitted and multiple instance become possible this reference will be replaced by a pair (InstanceID,ProjectID)
I also think it would be required to duplicate the EcoTaxa project Title in Ecopart
Perhaps it would also make sense to allow to map to a collection and not just a Project
The ecotaxa project is used for :
- Search matches between EcoPart et EcoTaxa sample
- Search criteria on the main screen

It may be possible to avoid 2 EcoPart project to reference the same EcoTaxa project but I'm not sure it's interesting.
Regarding UVP6, a same instrument in a same mission could be used in 2 differents projects, one as UVP Remote (theoriticaly without Zoo link) and one as UVP6 local.

**Comment by jiho** [comment]
I stand by my initial spec: one EcoPart project should correspond to one EcoTaxa project on one EcoTaxa instance. Then samples are matched within that project.
Collections will be used on EcoTaxa's side only, to allow homogeneous sorting.

When one EcoTaxa project is linked to several EcoPart projects, it will have to be split into several projects and a Collection containing all those projects will have to be created.

As of today, this is the (rather short) list of such projects

```
   ptitle                         pprojid projid title                                                    
   <chr>                            <int>  <int> <chr>                                                    
 1 uvp5_sn008_an1304                   56     41 UVP5 AN Arctique (an1304 an1405 an1407) part A to valida…
 2 uvp5_sn008_an1407                   59     41 UVP5 AN Arctique (an1304 an1405 an1407) part A to valida…
 3 uvp5_sn008_an1405                   57     41 UVP5 AN Arctique (an1304 an1405 an1407) part A to valida…
 4 uvp5_sn000_lter2008                  5     45 UVP5 CCELTER (Iter2008 ccelter_2012 ccelter_2014)        
 5 uvp5_sn000_ccelter_2012              3     45 UVP5 CCELTER (Iter2008 ccelter_2012 ccelter_2014)        
 6 uvp5_sn003_ccelter_2014             42     45 UVP5 CCELTER (Iter2008 ccelter_2012 ccelter_2014)        
 7 uvp5_sn002_moose_dyf_2017           14     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
 8 uvp5_sn002_moose_dyf_2016           13     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
 9 uvp5_sn002_moose_dyf_2018          166     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
10 uvp5_sn002_moose_dyf_2013           10     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
11 uvp5_sn002_moose_dyf_2014           11     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
12 uvp5_sn002_moose_dyf_2015           12     35 UVP5 Dyfamed 2013 2014 2015 2016 2017 2018               
13 uvp5_sn002_moose_ge_2013            15     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
14 uvp5_sn002_moose_ge_2014            17     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
15 uvp5_sn001_2012_moose_ge            21     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
16 uvp5_sn002_moose_ge_2015_filt…      31     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
17 uvp5_sn005_moose_ge_2013            55     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
18 uvp5_sn002_moose_ge_2016_filt…      18     30 UVP5 MooseGE 2012 2013 2014 2015 2016                    
19 uvp5_sn003_tara2013                 49    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
20 uvp5_sn000_tara2009                  6    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
21 uvp5_sn003zp_tara2012               51    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
22 uvp5_sn000_tara2012                  9    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
23 uvp5_sn000_tara2010                  7    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
24 uvp5_sn000_tara2011                 99    579 UVP5 Tara Oceans (tara2009, tara2010, tara2011, tara2012…
```

In all cases, it makes complete sense to have separate EcoTaxa projets for management and cleanness purposes and it will also make sense to have a Collection for homogenisation and export purposes.

**Comment by picheral** [comment]
I do agree. It will be quite easy to split the Ecotaxa projects and then modify the code.
