### ISSUE TITLE
Le statut "ExploreOnly" d'un projet ne fonctionne pas

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_front#486]
Lorsque l'on est dans un projet, qu'on fait "Project" -> "Edit project settings" -> qu'on choisit "ExploreOnly" dans "Status" ; les "annotates" du projet peuvent tout de même déplacer des vignettes alors qu'ils ne devraient pas

**Comment by grololo06** [comment]
Salut, quand tu écris "déplacer des vignettes", c'est quoi "déplacer"? Il peut changer la catégorie?

**Comment by Kikouliou** [comment]
Hello, déplacer veut dire mettre une vignette dans une autre catégorie (que ce soit par cliquer/glisser ou par le clavier)

**Comment by grololo06** [comment]
Contexte: Project 377, utilisateur Louis

**Comment by grololo06** [comment]
La fonction a été 'oubliée' lors du codage il me semble. 

Si le status n'est pas "Annotate", Il y a juste les menus de prédiction et d'import qui disparaissent (mais on peut quand même les lancer par l'URL du navigateur). Par contre, les menus d'effacement et de mass edit sont toujours là (et marchent!).

Bref il ne faut pas compter dessus pour protéger quoi que ce soit.

**Comment by picheral** [comment]
A résoudre ASAP pour protéger les jeux de données homogénéisées de TARA.... même si nous avons fait un backup !

**Comment by grololo06** [comment]
Avant ou après les _autres_ ASAP ? :)

**Comment by picheral** [comment]
On peut attendre. Nous supprime tous les status annotateurs en attendant.

**Comment by grololo06** [comment]
Tant qu'à implémenter, autant faire les spécifications, donc je passe en "to clarify". Je crois que, personne n'étant à l'abri d'une erreur, il faudrait protéger les projets importants des "Managers" aussi, voire même des admins :)

**Comment by picheral** [comment]
Le statut "Explore only" n'est activable QUE par les personnes ayant les droits de management. Il permet de verrouiller toute modification d'annotation. La spécification est donc simple !
Le principe de protection des projets "importants" est l'export backup.
La future page de recherche/sélection d'un projet permettra d'afficher le statut du projet ainsi que les commentaires sur le projet. Il pourra être utile d'afficher ces info dans le topper du projet ou dans la page About #382 .

**Comment by jiho** [comment]
Explore only doit donc empêcher toute modif y compris par le manager et les application admin.
Ces personnes peuvent le repasser en "Annotate" si besoin.

La spec est donc claire. J'enlève le `to clarify`

**Comment by picheral** [comment]
Empêcher toute modification de l'annotation (seulement) !

**Comment by picheral** [comment]
Je valide.

**Comment by grololo06** [comment]
Changement des settings possible, p.e. pour enlever l
Classification impossible
Import impossible
Delete impossible
Changement sample/acquisition/process impossible

Changer le nom du réglage: Explore Only->View Only.

**Comment by grololo06** [comment]
Vu le 25/05/2021: "Annotate no prediction" n'est pas mieux, comme indiqué dans mon commentaire + haut.
