### ISSUE TITLE
Allow and keep empty samples

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#489]
Linked with a comment in https://github.com/ecotaxa/ecopart/issues/5 , I don't think that there is, as of today, a clean way to have empty samples in the application.
The import is based on _existence_ of images + features, so we have to adapt something to allow emptiness.

Of course, consequences in code of the present assumption "an empty sample is useless and can be deleted" need to be removed as a first step.

BTW, is it an empty sample or an empty subsample (i.e. process+acquisition)

**Comment by jiho** [comment]
It is necessary for samples and subsamples.

The necessity comes from the fact that there are samples or subsamples (more frequently subsamples) without organisms in them. These 0 concentrations are ecologically relevant. They need to be accounted for.

Obvious example: UVP casts (=samples) with 5 m bins (=subsamples) in which no organism is seen; there will still be metadata associated with the subsample (volume imaged, depth min and max) and it is necessary to have the 0 #/m3 information to correctly compute average concentration per sample for example.

**Comment by grololo06** [comment]
Thanks for the background information, but _how_ to do it in practice?
Use case: 
- As an EcoTaxa user, I have collected an empty sample (e.g. a net full of nothing).
- I want to have it in the system, i.e. store somewhere the fact that in this time+place, 0 was collected in these 30m3 of water.

I open EcoTaxa, log in and then I... ???

A bit of usage background, **as of today**, one line of a TSV import file is one object + parent data + image. 
So the partial "solution" to do it is:
- add a line in a TSV with dummy data, import it 
- find the dummy object numerical ID
- delete manually the object using its numerical ID.

It's obvious that this hackish way of creating an empty sample cannot become "official".

Moreover, there are problems with the hackish empty sample freshly created:
- It will be erased during the "cleanup" procedure (easy to fix).
- It will be visible nowhere because a sample is visible only _from one of its enclosed objects_.
- It will be filtered out during export because of the TSV format (again).
- and many others I don't think about right now...

This requirement is a major shift in the model of the application as we go from 1->(1,n) to 1->(0,n) on some relations.

**Comment by grololo06** [comment]
Just an _import_ feature, allow to import an empty _acquisition_ with a special object_id 'empty' (in lowercase) by convention. 
A TSV file cannot contain _both_ the code for "no object" and an object for an acquisition.
After being created empty, the acquisition can be filled with objects during e.g.  other import operations.

**Comment by grololo06** [comment]
To check if we can get closer from #476 convention

**Comment by jiho** [comment]
## Import

Solutions considered:
1. several files, _à la_ DarwinCoreArchive
2. a convention to define a code for emptiness at object level

The first solution is too complicated for most users. It would required significant changes to the import code and to the software that prepares the data.

=> Choose a code to insert in the current format of the import file: `empty` 

So an import file with an empty subsample would look like

```
sampleid	sample_date	subsampleid	sub_depth	sub_vol	objid	obj_area	obj_mean
station1	20201012	layer1		2.5		3.56	s1_l1_a	124		45	
station1	20201012	layer2		7.5		2.1	s1_l2_a	34		245	
station1	20201012	layer2		7.5		2.1	s1_l2_b	334		23	
station1	20201012	layer3		12.5		3.5	empty	empty		empty	
station1	20201012	layer4		17.5		3.2	s1_l4_a	356		35	
station1	20201012	layer4		17.5		3.2	s1_l4_b	456		56	
```

## Life in the project

Once created, the empty (sub)samples should not be erased. 

The emptiness is not a characteristic of the sample/subsample = objects can be associated with it upon further imports.

## Export

For a regular, object level export, reformat the data as for import.

For a summary export (number of objects per category), add a category called `empty` and set its abundance to 0. We'll think about this further when we get a better summary export (with concentrations).

**Comment by grololo06** [comment]
There is a legitimate need for erasing empty samples:
- Import with a given sample_id
- Realize you want other names
- The app allows to remove all images, but sample orig_ids remain if they are not "automatically" cleaned up
