### ISSUE TITLE
Change the way to store `classif_id` and `classif_auto_id`

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#495]
Currently, the result of an automatic classification is stored in `classif_id` and `classif_auto_id` (I think) but with a status `P` is associated to the `classif_id`. So there is some redundancy. The separation of the two fields was to make it possible to compute a confusion matrix, which we decided to remove (#452).

There should be only fields:
- `classif_id` : taxo id assigned to object
- `classif_status` : P, V, D, NULL, etc.
- `classif_author` : currently a `user_id` or NULL, possibly a `model_id` in the future.
- `classif_datetime`

This will then enable the storage in history of the automatic classification and their potential reversal.

**Comment by grololo06** [comment]
Code says:
```
    classif_id = Column(INTEGER)
    classif_qual = Column(CHAR(1))
    classif_who = Column(Integer, ForeignKey('users.id'))
    classif_when = Column(TIMESTAMP)

    classif_auto_id = Column(INTEGER)
    classif_auto_score = Column(DOUBLE_PRECISION)
    classif_auto_when = Column(TIMESTAMP)

    classif_crossvalidation_id = Column(INTEGER)
```
classif_crossvalidation_id is always NULL in the prod DB -> remove
classif_auto_id is classif_id for a non-human author
classif_auto_when is classif_when for a non-human author
classif_who can become classif_author if we remove the FK on user and adopt a convention, e.g. id < 0 means non-human.
We keep the classif_auto_score I guess? Or need more space for ML quality indicator?

**Comment by jiho** [comment]
I see things in `classif_id` with a status `P` so it seems classification stores the id in both places.

As for the storage of the classification, we need at least one score but we discussed the possibility of the best n scores after classif. But this is for later (we need an UI to use this too).

**Comment by grololo06** [comment]
The DB is full of inconsistencies on this front, no big surprise. We have 10M objects predicted with no auto_id or auto_date, due to previous versions of the code or direct DB update or whatever.

**Comment by grololo06** [comment]
One more, objects validated with no date:
```
 ecotaxa=# select count(*) from obj_head where classif_qual in ('V','D') and classif_when is null;
  count  
---------
 2357190
(1 ligne)
```

**Comment by grololo06** [comment]
Objects with a qualification but no date whaetever:
```
ecotaxa4=# select count(*) from obj_head where classif_qual is not null and classif_when is null and classif_auto_when is null;
  count  
---------
 9044097
(1 ligne)
```

**Comment by grololo06** [comment]
No qualification but a category:
```
ecotaxa4=# select count(*) from obj_head where classif_qual is null and classif_id is not null;
 count  
--------
 147654
(1 ligne)

Temps : 400,166 ms
```

**Comment by grololo06** [comment]
Validated or set to Dubious by nobody:
```
ecotaxa4=# select count(*) from obj_head where classif_qual in ('V','D') and classif_who is null;
  count  
---------
 5687043
(1 ligne)

```

**Comment by grololo06** [comment]
Predicted with a specific auto_id, i.e. prediction is not user-visible:
```
ecotaxa4=# select count(*) from obj_head where classif_qual='P' and classif_id != classif_auto_id;
 count 
-------
 69101
(1 ligne)
```

**Comment by picheral** [comment]
The DB is full of inconsistencies on this front, no big surprise. We have 10M objects predicted with no auto_id or auto_date, due to previous versions of the code or direct DB update or whatever. I did not dig in history table but I guess it's worse there.

Des objets été importés comme PREDICTED quand leur classification a été faite en dehors d'Ecotaxa. Cela explique probablement l'absence de auto_id ou auto_date...

**Comment by picheral** [comment]
Je pense qu'on a plein d'inconsistances dues à ces classifications externes et au manque de sécurisation du ré-import des TSV en utilisant la classification externe. Le grand nombre me fait pencher vers des projets UVP5 traités par Morphocluster ou prédits par Rainer/Martin. Je pense que je pourrais aussi vérifier les nombreux projets traités par PKId et récupérés via Zooprocess...

**Comment by grololo06** [comment]
Backend code should not allow inconsistent input anymore, DB cleanup "soon".
