### ISSUE TITLE
Allow users to edit their information

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#513]
Instead of "Change password" (top right menu), add "Edit my profile" which links to a page to edit all user properties (name, institution, email, password etc.).

If changing the password on this page makes it too complicated, keep it on a separate page (but I would rather have all in one page).

**Comment by jiho** [comment]
Question: what happens when a user changes his/her email which acts as a login? No problem to log back?

**Comment by grololo06** [comment]
Linked with #192 and probably others. It would be good to gather all of them in a single issue.

**Comment by grololo06** [comment]
#193 looks like this one but accessible from managers.

**Comment by picheral** [comment]
Clarifier le cas des utilisateur qui passent d'une institution à une autre sans changer de compte (adresse email).

**Comment by jiho** [comment]
The API documentation for PUT users/{userid} states:

```
An administrator or user administrator can change any field with respect of consistency.
A user can update own password and mail.
An ordinary user cannot update anything for another user.
```

I suppose that institution etc. are also changeable. If so it should be documented in the API.

It also means that the backend pieces are there for a UI to be built to update the user info.

**Comment by grololo06** [comment]
> users/{userid}

The doc is in line with the code: https://github.com/ecotaxa/ecotaxa_back/blob/b2b924bdcfdf3b9da98c2c79512fa0d7c9de7e95/py/API_operations/CRUD/Users.py#L78

As of today, users can only change own name and password.

**Comment by jiho** [comment]
I was rather for changing the documentation to reflect the fact that a user can change any field than to change the code to reflect the limitations in the documentation 😉

**Comment by grololo06** [comment]
Code extract:
```
elif current_user.id == user_id:
            cols_for_upd = [User.name, User.password]
```
To read: if current user is changing own account, then "columns for update" are name and password.

I adjust the doc.

On the Web, generally mail addresses are verified using a link so #735 would be needed.
