### ISSUE TITLE
Enforce bounds for standard fields

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#531]
EcoTaxa defines a few standard fields that can be queried and/or used for export (#520). Those need to contain valid data and we should implement checks at import (and back-propagate those in existing data):
NB: tick when check implemented

- [ ] depth, m. range : [0,11500]
- [x] longitude, º [-180,180]
- [x] latitude, º [-90,90]
- [ ] date [1900;2100]
- [x] time [00:00, 24:00] (NB: should probably be checked together with date)
- [ ] subsampling:
     - if binary splits, usually noted as number of splits (subsampling rate = 1/number of splits), should be 1 to +inf and a power of two;
     - if directly the subsampling rate (i.e. the result of 1/number of splits or another way to compute it), should be in [0,1]; 
- [ ] volume, m3 ]0,50000] (NB: 0 is not valid)

When the column is absent from an import, then it is filled with NULL. Easy.

When the column is present but the value is absent for a certain row, I assume it is filled with NULL too. @grololo06 is that the case?

The question is what to do when the values are valid for some rows but invalid for others: either reject the whole import or warn and replace the erroneous values by NULL. The second behaviour would allow for missing value codes such as 99999 for a depth, or 999 for a longitude.

**Comment by grololo06** [comment]
Yes the DB column takes NULL when there is a TSV column with no value, and NULL everywhere when the TSV column is not present.

**Comment by grololo06** [comment]
Subsampling: 999
Volume can be 999999. 
TODO @grololo06 : Check in DB for EMODnet export and verify what is valid (or not).

**Comment by grololo06** [comment]
Decision made 11 March 2021:
About values check: Warning during import (but not blocking) if any string made only of "9"s  and length > 2 is present in a volume-related column e.g. tot_vol free field.
