### ISSUE TITLE
When a category is selected, do not display its name under every single image

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#551]
Could reduce visual cluter on pages with lots of objects.

![Screenshot 2020-12-17 at 09 49 04](https://user-images.githubusercontent.com/18445/102464998-666cd500-404d-11eb-9e00-934d51acfc0d.png)

**Comment by grololo06** [comment]
Globally validated by a sample of users, under the condition that the current category is more visible.
