### ISSUE TITLE
Consider moving the layout of the classif page to using free flowing <div>s

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#575]
It would:
- solve some layout problems (#371)
- allow images to reflow when the window is resized without manual reloading 
- resonate better with current web standards

But it would
- look a bit different
- make it a bit harder to use the fit mode

Here are layout tests with some CSS +JS to get started (including some with a solution for the "fit" mode):
[layout_tests.zip](https://github.com/ecotaxa/ecotaxa_dev/files/5850717/layout_tests.zip)

**Comment by grololo06** [comment]
As stated during a discussion, it will be difficult to maintain per row selection.

**Comment by grololo06** [comment]
In fact, the main problem is not to select a line (some JS would do) to display the selection button. A column not part of the flowing vignettes maybe.
