### ISSUE TITLE
Common syntax for all filters except category/taxonomy

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#592]
Utiliser:

- espace ou * ou % comme wildcard (i.e. regexp .* )
- insensible à la casse
- wilcard automatique à la fin
- AVEC wildcard auto au début

Applies to:
- project name filters
- sample name filters
- username filters
- instrument name filters

-> Propagate in API

**Comment by grololo06** [comment]
[ ] Do an inventory
[ ] Use a single component

**Comment by grololo06** [comment]
To re-shuffle per-page one day.

**Comment by bea777515** [comment]
use only space as wilcard = simpler!
