### ISSUE TITLE
Add keyboard shortcuts to assign a category

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#618]
## Use case
Within a category, the objects are often confused with the same set of other categories (e.g. in Calanoida, confusion with other copepod taxa). When validating the sorting, one has to often type the same names again and again. It would be faster to select a few objects and press a key to assign the category.

Configuring a keyboard shortcut would also allow to configure mouse buttons or graphic tablet button to assign a category, since those often emulate a keycode.

Keys that do not conflict with much and would be natural to assign `n` categories are F1 to F12.

## Implementation:
- Right click on a category, show the menu "Assign shortcut"
- Upon hovering the menu item, open another side menu with F1 to F12 as choices; choices already taken are highlighted (italicised) but it is still possible to choose one and it is then reassigned the to current category
- Once the shortcut is chosen, it is displayed at the right of the name of the category
- Pressing the shortcut key assigns the category to the selected items and switches the current category to it (=> it is shown in the top box, it is highlighted in "yellow" in the list, and Ctrl+D assigns this category)

**Comment by rkiko** [comment]
I would not use F1 to F12, my Mac does not have them. Shift and a letter or number will be better... Depends on existing shortcuts...

**Comment by grololo06** [comment]
Linked with #173
