### ISSUE TITLE
Allow to choose the variable (abundance, concentration, biovolume) for summary export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#620]
The summary and dwca exports can be in terms of abundances #615, concentrations #616, or biovolume #617.

The UI for summary export (for now) there should read:

Export <kbd>abundance</kbd> per category and <kbd>sample</kbd>.

Where:
- <kbd>abundance</kbd> is a select menu with choices abundance, concentration, biovolume
- <kbd>sample</kbd> is a select menu with choices sample, subsample.

Concentration is available as a choice when the appropriate fields (total volume and subsampling coef) are specified in project settings (#619).
Biovolume is the same but needs individual volume to be specified too.

When abundance is chosen, sample and subsample are available.

When concentration or biovolume are available, sample or subsample is chosen automatically depending at which level the total volume is specified (cf #616 ).

**Comment by grololo06** [comment]
Present code (in EcoTaxa front-end) is in class ExportJob and export_create.html template.
The code should be amended to include variable choices depending on the project variables.
The following:
> When concentration or biovolume are available, sample or subsample is chosen automatically depending at which level the total volume is specified (cf https://github.com/ecotaxa/ecotaxa/issues/616 ).

Means that the API has to expose somehow the _location_ of variables, not only their existence, in order to be able to propose relevant choices.

**Comment by grololo06** [comment]
Present code also allows "no aggregation", do we keep/drop ?

**Comment by jiho** [comment]
As far as I can see, the summary export is per project, sample, acquisition/subsample. We should keep all those.

The variable exported now is abundance. Concentration and biovolme should be added if the variables necessary to compute them are identified in project settings.

**Comment by grololo06** [comment]
Hopefully the API doc & various tests in the back-end will be good examples for UI implementation.
