### ISSUE TITLE
Improve automatic checks on docker production

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#622]
Follow-up to the incident (causing unplanned downtime) seen on feb 11 2021.
Symptom: During startup, the docker image was looping on an error due to missing package "httptools" and not responding any request.
The cause in was a version bump of uvicorn to v 0.13.3
The dependency between uvicorn and httptools is not static in the code but used at runtime.

The fix was simply https://github.com/ecotaxa/ecotaxa_back/commit/a7afc30b2953c5d5cf5057eecfc2210d53042d70

While dev configuration intends to be identical to the docker one, the problem was not seen during development because 
httptools had been installed once (for any reason, probably a reversed version bump attempt), and remained there (in the venv) since.

While QA test configuration intends as well to be identical, the used test automation tool (tox) maintains a cache of libraries (.tox) which contained as well the library, so all tests ran fine.

The docker build went fine, but the docker test script https://github.com/ecotaxa/ecotaxa_back/commit/2c50457972b1c11e62b3e998aa9fe989396becff was running a _fixed_ version of the image (2.5):
```
Index: docker/run_docker.sh
diff --git a/docker/run_docker.sh b/docker/run_docker.sh
@@ -8,7 +8,7 @@
 --mount type=bind,source=${PWD}/../../ecotaxa_master,target=/ecotaxa_master  \
 --mount type=bind,source=/var/run/postgresql,target=/var/run/postgresql  \
 --mount type=bind,source=/home/laurent/Devs/ecotaxa/SrvFics/,target=/plankton_rw \
-grololo06/ecotaxaback:2.5
+grololo06/ecotaxaback
 # Add this in the end to skip the init
 #bash
```

So whatever was done, the problem seen in production was always present... 

TODO in order to avoid repetition:

- [ ] Ensure that dev venv is in <-> sync with requirements.txt
- [ ] Ensure that tox venv is cleaned before a release. It cannot be for each test as it's quite long
- [ ] Write auto tests of run.py for both servers (uvicorn and gunicorn)
- [ ] Ensure that the tested docker image is the right one

**Comment by bea777515** [comment]
add a detection routine of ecotaxaback IP  by  ecotaxafront 
(depending on the starting order of the containers  ecotaxafront is not starting correctly )
