### ISSUE TITLE
Common variables/formulas to add for Flowcam and IFCB projects

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#635]
Just to keep track, see attached.

[formulas.zip](https://github.com/ecotaxa/ecotaxa_dev/files/6034855/formulas.zip)

**Comment by jiho** [comment]
That said, the decision to have a formula interface for subsampling, water volume and individual volume should cover all these cases. We cannot implement the various scenari, hence the generic solution.
