### ISSUE TITLE
Deal with import of 'old' exports containing deprecated taxa

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#647]
Once #509 is implemented, it will not be possible anymore to re-import an export zip with deprecated IDs.

**Comment by picheral** [comment]
Proposer un mapping à l'import ?

**Comment by grololo06** [comment]
Oui, enfin ce sera plus "informer du mapping" que "proposer un mapping", puisque les taxa 'deprecated' on ne peut plus rien mettre dedans.

**Comment by grololo06** [comment]
Just saw from the code that if "renamed", a taxon just disappears from EcoTaxa.
