### ISSUE TITLE
Mise à jour asynchrone des statuts de task

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#661]
Pour l'instant le status est rafraîchi quand la page est rechargée.

**Comment by jiho** [comment]
Plus généralement, il faudrait un système de notifications indépendant du changement de la page (import fini, prédiction finie, alerte de maintenance, etc.)

Une raison d'aller vers Vue.js ou cela est possible sans?

**Comment by grololo06** [comment]
C'est possible sans Vue e.g. avec JQuery.
