### ISSUE TITLE
Sélection de catégories pour créer des subset

### ISSUE THREAD

**Issue by Kikouliou** [ecotaxa/ecotaxa_front#685]
Il serait pratique de pouvoir sélectionner des catégories dans lesquelles on souhaite faire un subset. 
On pourrait le mettre à cette étape ici : 

![image](https://user-images.githubusercontent.com/33952113/121648147-76fb8680-ca97-11eb-9f41-e308613df507.png)

Au niveau de "per category", mettre une liste déroulante pour sélectionner des catégories.

**Comment by jiho** [comment]
Il suffit de faire un filtered > subset.

**Comment by jiho** [comment]
Mais il faudrait une sélection multiple de catégories sur la page de classif!
