### ISSUE TITLE
Allow project manager to delete samples and subsamples (=acquisitions)

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#692]
To be added in the project settings. List the samples, with number of images per (sub)sample and allow to delete the empty ones, with a clear warning: "Empty (sub)samples may occur and are necessary to keep for EcoTaxa to correctly compute concentrations of zero. Remove them only if they result from a mistake"

**Comment by jiho** [comment]
This deletion used to be automatic, for samples and acquisitions, it should not be since empty samples are theoretically possible and empty subsamples/acquisitions will occur. They should be kept to compute concentrations.

**Comment by grololo06** [comment]
To merge somehow in present "delete objects"

**Comment by jiho** [comment]
The (sub)samples that are imported empty should stay that way and the (sub)samples that are made empty by the deletion of objects should indeed be deleted.

So this should be coupled with the deletion of objects indeed.
