### ISSUE TITLE
Create an "About EcoTaxa" page

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#701]
Content:

_EcoTaxa is a web application dedicated to the visual exploration and the taxonomic annotation of images that illustrate the beauty of planktonic biodiversity._

[Image plancton]

If you use EcoTaxa in your work, we would appreciate if you cite it as: Picheral M, Colin S, Irisson J-O (2017). EcoTaxa, a tool for the taxonomic classification of images. http://ecotaxa.obs-vlfr.fr.

The development of EcoTaxa is made possible by the support of:

[Pour chaque point, logo sur la gauche, texte sur la droite]

- [Logos SU et CNRS] [Sorbonne Université](https://www.sorbonne-universite.fr) and [CNRS](http://www.cnrs.fr), who pay the salaries of the permanent staff overseeing its development.
- [Logo Oceanomics] The [Programme Investissements d'Avenir](https://www.gouvernement.fr/le-programme-d-investissements-d-avenir) that funded the development of the original version of the application through the project [Oceanomics](http://www.oceanomics.eu), dedicated to the analysis of the [Tara Oceans](https://oceans.taraexpeditions.org) samples [45k€]
- [Logo PUF] The [Partner University Fund](https://face-foundation.org/higher-education/partner-university-fund/) that funded the hardware on which EcoTaxa ran for several years and the machine learning solution it permitted, through a joint project between Université Pierre et Marie Curie (now Sorbonne Université) and the University of Miami [15k€]
- [Logo LEFE] The [CNRS LEFE program](https://programmes.insu.cnrs.fr/lefe/) that allowed to renew the machine learning backend, through the project DL-PIC [10k€]
- [Logo Belmont Forum] The [Belmont Forum](https://www.belmontforum.org), which funds an overall review of the application through the [WWWPIC](http://site.wwwpic.net/) project [500k€]
- [Logo Watertools] The [Watertools](http://www.watertools.cn) company, who donated money to make the interface of EcoTaxa easier to translate, in Chinese in particular [30k€]

The maintenance of the software and hardware that allows EcoTaxa to run depends on the support of its users, who can be officially billed by the [Quantitative Imaging Platform of Villefranche](https://sites.google.com/view/piqv). We would very much appreciate if you would consider setting aside some funds in your next grant for this. [Contact us](mailto:piqv@imev-mer.fr) to estimate what would be both reasonable and useful.

The persons who made EcoTaxa possible are:
- Marc Picheral and Jean-Olivier Irisson: specifications and project supervision
- Sébastien Colin: initial specification
- [Altidev](https://www.altidev.com), Laurent Salinas, Laurent Reese: development
- Simon-Martin Schröder, Benjamin Graham: deep learning implementation
- Amanda Elineau, Corinne Desnos, Laetitia Jalabert and the [COMPLEx team](https://lov.imev-mer.fr/web/team-complex/) or the [Laboratoire d'Océanographie de Villefranche (LOV)](https://lov.imev-mer.fr/): testing and feedback

Disclaimer: If you annotate images in EcoTaxa you cannot claim for any retribution from the application managers but you can then download and use the results of your work. Even if they make their best to keep the application stable and secure, the managers of the EcoTaxa application are not liable for the safekeeping of the images and associated data it hosts. You are responsible for performing regular backups.

**Comment by jiho** [comment]
@picheral can you please review the content above and let me know if I forgot a funding source?

**Comment by jiho** [comment]
Once this is implemented, remove:
- the "Ecotaxa is a web application..."
- the logos
- all the text that follows
from the landing page. But add a link: "About EcoTaxa" there.

There should be a link in the top right menu too.

**Comment by picheral** [comment]
OK pour les sources de financement d'ECOTAXA (et pas d'EcoPARYT).

**Comment by LaurentReese** [comment]
agreed between JO and Laurent R:
URL links should be available when clicking on the logo (part on the left) or on the text (part on the right).
The Generic panel (with the menu on the right) should be integrated in this page

**Comment by LaurentReese** [comment]
Link from historic EcoTaxa to this new page will be done at the end.
For the moment, add the page in the following link : https://ecotaxa.obs-vlfr.fr/front/ecotaxa_about

**Comment by LaurentReese** [comment]
Laurent R :  ==> Study a solution with REST API calls to https://www.deepl.com/docs-api, in order to automatically translate texts on-the-fly, instead of a heavy pre-translation work : as many tables as supported languages, and in each table, as many entries as strings. Plus, of course, new work in every table each time a string is added/changed.

**Comment by LaurentReese** [comment]
After meeting today (JO, Marc, Laurent  S, Laurent R) :
=> manual translations (one table for each language) instead of automatic Deepl API calls.
=> Make the loggos bigger (inspire from historic EcoTaxa site).
=> align logos in a box on the left, align the texts in a box on the right, in front of the corresponding logos.

**Comment by LaurentReese** [comment]
https://github.com/ecotaxa/ecotaxa_dev/issues/701#issuecomment-877867515 needs to be done (probably by Laurent S)

**Comment by LaurentReese** [comment]
Problem described here to discuss with J.O.
https://github.com/ecotaxa/ecotaxa_dev/issues/701#issuecomment-877867515
