### ISSUE TITLE
Left pane counts do not reflect current filtering.

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#743]
Before:
![image](https://user-images.githubusercontent.com/20199778/137344643-87b52752-7340-41b3-a519-7d8f8dbfe444.png)

After filtering using b1 sample:
![image](https://user-images.githubusercontent.com/20199778/137344562-16740af4-557f-402a-aacb-b6402a1afdaa.png)

The global count in the header is updated to reflect the filter, but not the count per taxon.

So e.g. by selecting a category which is absent from the filtered dataset:

![image](https://user-images.githubusercontent.com/20199778/137345184-8a8918c0-b3a4-4226-b3f8-8c90b0583c99.png)

**Comment by picheral** [comment]
Après enquête, la PIQv préfère bien que le panneau de GAUCHE !!!!! reflète bien le filtre et se mette donc à jour.
