### ISSUE TITLE
Choosing to use deep learning features without a deep learning network makes prediction stop

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#748]
e.g. task 48898 in project https://ecotaxa.obs-vlfr.fr/prj/3904

In project settings, the deep learning feature extractor is not selected.
The first page of the prediction mentions this.
But the last page still allows to keep "use deep learning features" selected.
The result is an error message : "SavedModel file does not exist at: /home/ecotaxa/ecotaxa/TF_networks/io_/feature_extractor/{saved_model.pbtxt|saved_model.pb}"

Expected behaviour:
- Use deep learning features should be greyed out and unticked, with an informative message as to why and how to fix it
or
- The prediction should fail with a more informative error message (explaining why and how to fix it)

**Comment by jiho** [comment]
Assigning @grololo06 again since you did the prediction pages fairly recently. Since then this pb has come up quite often and it would be nice to fix it if it is as easy as I suppose (it may not be).

There is a mechanism to disable the selection deep features, when the deep feature extractors are not the same across projects. I guess you should add that if they are the same but equal to "" it should be disabled also. Indeed, in all occasions  when this problem arose (that I know of), it was because no model was selected as the deep feature extractor.

**Comment by grololo06** [comment]
This is due to a (probably) historical value '' (empty string) in projects.cnn_network_id. The code tests sometimes for None aka NULL and sometimes it works as well for this ''.

**Comment by grololo06** [comment]
Hum, no the '' comes from plain UIs (old and new one), so not an historical issue. Fixed anyway.
