### ISSUE TITLE
Merge allows objects with the same original object id to coexist in the same project

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#777]
Procedure:
1. go project A
2. take a subset A1
3. take the same subset A2
4. merge A2 into A1

Expected:
The merge procedure should complain that the original object ids are the same and should either fail or (ideally) offer the merge the non duplicated objects and discard the others.

Actual:
The merge goes on and the objects are duplicated in A1

Example:
- take two 100% subset of https://ecotaxa.obs-vlfr.fr/prj/185?taxo=84993 (one object as of now)
- merge the susbets, which results in https://ecotaxa.obs-vlfr.fr/prj/5468

**Comment by grololo06** [comment]
#548 #547 #747
