### ISSUE TITLE
Subset looses the information about who made the annotation

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#781]
Taking a subset of a project creates the objects in the destination project, their identification is visible but the person who did the identification disappears.

Example:

From https://ecotaxa.obs-vlfr.fr/prj/185?taxo=84963&taxochild=N&ipp=1000&zoom=30&sortby=classif_auto_score&magenabled=0&popupenabled=0&statusfilter=V&sortorder=desc&dispfield=+dispfield_classif_auto_score&projid=185&pageoffset=0 use Filtered > Subset to take a 10% subset.

The result is https://ecotaxa.obs-vlfr.fr/prj/5549 where the images have the correct identification (detritus) but no user associated to it.

The user responsible for the annotation is an object level information that should travel with the object in the new project, even if the user in question does not currently have permissions in it.

**Comment by grololo06** [comment]
Technically, nobody validated the clone, so this is correct. -> Feature.

**Comment by jiho** [comment]
The information transferred to the subset should be at least the latest annotator and, if possible/not too complicated the whole annotation history.

**Comment by jiho** [comment]
We're in the process of assembling datasets to serve as reference. This is done by subsets and merge. This new way of working means we loose all track of who validated the object before and therefore cannot attribute the work to the right people.

The proper way of doing this would probably be to allow an object to belong to two datasets, sharing its history and annotations. However, this will lead to a nightmare in terms of permissions etc. so the feasible way of doing this now is to restore the old behaviour and implement what is above:
- transfer the latest annotator, at least
- duplicate the whole validation history (we don't care about predictions) ideally.

This is relatively urgent given the current context.

**Comment by grololo06** [comment]
Solved o, 2.6.6.
Noye that I did not bother filtering out non-human historical lines.
