### ISSUE TITLE
Add link to image in .tsv export

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#797]
To be able to make analyses using some but not all images of a project, the only solution now (excluding the API) is to download the whole project with images. It is overkill. It would be ideal to add a link to the images in the tsv export.

Several solutions:

1. choose the rank of the image to export and just add the column: the rest of the structure of the file (in particular the number of lines) is not changed. Pros: simpler handling of exported files; Cons: more options in the UI

2. systematically include the link to all images, meaning all other lines will be duplicated if there are two images per object. Pros: trivial in the UI; Cons: complicated procedure to get unique objects

**Comment by grololo06** [comment]
Good idea but what about data ownership? Even if images are not "so well" protected by now, it could be improved/changed in the future.
