### ISSUE TITLE
Change the default export format for date and times to ISO 8601

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#829]
Currently the option is called "Format dates and times using - and :". Otherwise date and times are exported as numbers; this is prone to mistakes (esp because of leading 0).

- [ ] Make the format YYYY-MM-DD HH:MM:SS.SSS (when milliseconds will be available #696) the default
- [ ] Rename the option to "Instead of ISO 8601, use the old format for dates and times (YYYYMMDD and HHMMSS as numbers)", deactivated by default

**Comment by grololo06** [comment]
I tagged the option as UI, as we could as well invert the default in the API definition but it's simpler to do it on one side.
