### ISSUE TITLE
Creation of an upload service to replace the FTP

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#832]
The global FTP server presents issues (FTP, as a protocol, is apparently not the most secure; it requires a separate server to be running and maintained; the data uploaded by anyone is readable by everyone; the data needs to be purged etc.)

A new solution is needed. Several possibilities:

1. just suppress the FTP server and force everyone to go through the zip file upload or automate this through the API. If we provide scripts to do so, it may be a viable solution.
2. integrate a Python-based FTP server that would work for each user with the login and password of EcoTaxa; see https://github.com/ecotaxa/ftptest
3. use a different technology but with the same idea (e.g. webdav) that would allow people to drop a lot of data at once and leave this running before doing the import.

There was a question about group-level permissions (for someone to upload and someone else to import) #239 ; I suggest we drop it at first, the issue is complicated enough without it.

**Comment by grololo06** [comment]
There is a primitive API https://ecotaxa.obs-vlfr.fr/api/redoc#operation/list_user_files but it does not support e.g. resuming a big upload

**Comment by grololo06** [comment]
So, more precisely, the API is used for this front-end function:
![image](https://user-images.githubusercontent.com/20199778/176989142-a71e24cb-d0ca-400c-9c4a-8c6be5446ea7.png)
where there is typo (> instead of <)
Judging from the content of /tmp in the back-end docker, the API is quite used. I notice that however, there is a user folder _per_ operation (random names for security). 
Of course it's /tmp so the directories will not persist after a docker restart.
On code side, all is here: https://github.com/ecotaxa/ecotaxa_back/tree/master/py/FS

**Comment by grololo06** [comment]
The back-end is on FastAPI, i.e. ASGI, so if going to WebDAV (which sounds quite OK), we have e.g. https://github.com/rexzhang/asgi-webdav/tree/main/asgi_webdav
The tricky part will be authentication but at least it's same language and protocol as what we use.
Going for a test run (there is a docker image), I just found a bug that a symlink pointing outside the served directory provokes an error, but once the symlink removed, I get this on localhost:8000:
![image](https://user-images.githubusercontent.com/20199778/176990547-82b94cb6-0da9-43ac-ab5c-8800ab0793d8.png)
More interesting, I have this on my Linux box:
![Capture d’écran de 2022-07-02 09-10-33](https://user-images.githubusercontent.com/20199778/176990648-23e6f404-766f-4d9b-9e55-b45bfdfbb77e.png)
And basic operations work, properly traced:
```
INFO: [asgi_webdav.server] 172.17.0.1 - "GET /export_3847_20211023_0506.zip" 200 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /export_3847_20211023_0506.zip" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /export_3847_20211023_0506.zip" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /export_3847_20211023_0506.zip" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /export_3847_20211023_0506.zip" 207 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PUT /export_3847_20211023_0506.zip" 201 Basic - gvfs/1.36.1
INFO: [asgi_webdav.server] 172.17.0.1 - "PROPFIND /export_3847_20211023_0506.zip" 207 Basic - gvfs/1.36.1
```

**Comment by grololo06** [comment]
The pointed-at package code quality is very OK, so 
### Todo on back-end dev side:
Interface with EcoTaxa auth. 2 auths needed maybe, as asking users to extract their token for mounting a remote drive is very tricky at the moment. Or expose it somewhere in the front-end with explanations. The token would expire however.
Customize (we want to restrict some file types I guess, not a general purpose shared drive). 
Implement quotas (to prevent abuse).
### Todo on test side:
**Not automated**: take a very large file from present FTP and see if it can be uploaded. Optionally cut the network link on purpose to see how it behaves.
Automated: the usual pytest stuff for various entry points. Get/Put/Delete, etc.

**Comment by grololo06** [comment]
**Not explored:**
Apparently WebDAV does not support chunked upload i.e. resume, finding the biggest FTP file and trying it would probably be a first step.
Client (navigator) side. There a JS webdav _lib_ and maybe this one works out of the box. https://github.com/dom111/webdav-js
The possibility to have a dedicated (i.e. _not_ in EcoTaxa source tree) WedDAV server and have the back-end 'just' act as an authentication server. 
The opened question around sharing data #239

**Comment by jiho** [comment]
I think mounting a webdav share on their personal machine is beyond the skills of many non-API users (the targets for this approach). The recommandation will be to use a client like FileZilla which can do WebDav. This way, it seems that authentication with user+pass (same as on EcoTaxa) would be easiest. That said, the absolute easiest would be a client on the front that communicates with a webdav server on the back. The client on the front would be a file browsing interface in the import page when people can drag and drop files from their own machine, delete existing files, overwrite when the file/folder exists etc. Is the webdav js lib does that, then it looks perfect.

NB: For API users, they can either use the equivalent to the "single file upload" in the import page (functional now) or they would have to upload to webdav using whatever means they prefer (mounting, client, etc.) and then trigger the upload.

That said, if webdav is non-resumable, then maybe FTP is still the right horse...

**Comment by grololo06** [comment]
Random thoughts & findings:
People get used to remote drives with all the general public solutions around.
WebDav seems only available to "pro" version of FileZilla which costs 20€. 
I think we can forget about FTP which comes with bunch of technical constraints and problems.
Apparently "resume" is implemented in custom ways in various WebDav solutions, so indeed mastering both server and JS client would do.

**Comment by jiho** [comment]
webdav seems to be a no-no also. Waiting for more info but it looks like only a temporary file upload to the webpage, using http(s) will be acceptable. In a sense, this is what https://ecotaxa.obs-vlfr.fr/api/redoc#operation/post_user_file is doing, so we're good. But we would need to implement multiple file upload, possibly some permanence of the uploaded files, etc.

**Comment by bea777515** [comment]
maybe do all the work client side : 
webworkers / filereader / streams /
https://developer.mozilla.org/fr/docs/Web/API/Web_Workers_API
https://api.video/blog/tutorials/new-video-uploader-javascript-library
https://developer.mozilla.org/en-US/docs/Web/API/Blob
https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications
