### ISSUE TITLE
Limitation sur la longueur du Titleid or Project Title in the Ecotaxa export

### ISSUE THREAD

**Issue by picheral** [ecotaxa/ecotaxa_front#837]
Hi team,

 

I am looking for an option how we can take TitleID or Project Title along in our exports.

Now, our samples have a structured filename (eg “Valid_202105_TA113920_230_sub16_r1”) but the export (Backup export ready to re-import datasets, possibly including images)  does not allow to take along this important field.

 

Thanks in advance!

Jonas

**Comment by grololo06** [comment]
Hello,
Je n'ai pas tout le contexte mais le mail de Jonas ne me semble pas correspondre au titre de la présente. Il me semble qu'il veut avoir le titre du projet "quelque part" dans le .zip produit?
Effectivement, le zip a dans son nom le _numéro_ du projet et le titre n'est nulle part. On pourrait ajouter un .json dans la racine du zip (similaire au .log) avec quelques métadata sur le projet lui-même. Mettre le titre dans le nom de fichier du .zip ouvrirait la voie à bien des ennuis :)
