### ISSUE TITLE
Entity Relationship around concentrations and biovolumes calculations

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#843]
First proposal:

A "standard variable" has a "short name" and associates a "BODC term" with a "python expression".

The three possible "BODC terms" are:
  | Link                                     | Short name |
  | http://vocab.nerc.ac.uk/collection/P01/current/SSAMPC01/1/ | subsample_coef |
  | http://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/ | total_water_volume |
  | http://vocab.nerc.ac.uk/collection/P01/current/CVOLUKNB/ | individual_biovolume |

The "python expression" is a string which contains a syntactically valid python expression, evaluating as a number.
The "python expression" can reference, i.e. contain, only:
- Arithmetic operators
- Numerical constants
- Project free columns, by their CSV names, e.g. `sub_part`
- Standard python library math calls, e.g. `math.sqrt`

A Project contains at most one `subsample_coef` variable.
A Project contains at most one `total_water_volume` variable.
A Project contains at most one `individual_biovolume` variable.

**Comment by grololo06** [comment]
After reading the issues, it could be that linking somehow to instrument would be relevant and less painful to users, but of most importance for now is the cardinality, e.g. is there a single "python expression" for each "standard variable" per project. Any forgotten constraint (or lack of) here will have to be propagated from DB to UI, so costly in the end.

**Comment by grololo06** [comment]
I'm not (on purpose) referencing all the origin issues which are quite huge to read.
Also adding Bea in this simplified issue.

**Comment by picheral** [comment]
Yes for Zooscan and UVPs which represent a huge part of the database.

Not for the other instruments for which we do not control the metadata.

The FlowCam is in-between.

**Comment by jiho** [comment]
Yes there is (or at least we will support) only one formula per variable per project. A project is a unit of data, sharing metadata conventions; these are part of the convention.

To make it convenient the user, what is planned is that the formulas can be imported from another project. This is consistent with many other per-project settings and caters for all situations: both for instruments for which the formula is always the same (e.g. Zooscan: just pick any zooscan project and the formula should be OK) or for instruments for which the formula may change (e.g. FlowCam: pick a project in which the flowcam protocol was the same).

**Comment by grololo06** [comment]
@jiho It looks like the third one should rather be "Individual object volume in mm3", named "individual_volume" and _without_ any BODC term? The BODC term applies to the result of computation.

**Comment by grololo06** [comment]
Implemented in 2.6.8

**Comment by grololo06** [comment]
Final version of the data to store/edit:

The three possible "BODC terms" are:
  | Link or definition                                     | Short name |
  | http://vocab.nerc.ac.uk/collection/P01/current/SSAMPC01/1/ | subsample_coef |
  | http://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/ | total_water_volume |
  | Individual object volume in mm3 | individual_volume |
