### ISSUE TITLE
Sometimes user can't register and send us an email for account creation

### ISSUE THREAD

**Issue by juliecoust** [ecotaxa/ecotaxa_front#852]
When we do it same way same info on our side, it works. Maybe just tell them to try again later will help.

Exemples of user request : 

![image](https://github.com/ecotaxa/ecotaxa_front/assets/90832786/b468445c-6fa5-418f-83ed-ff85d8f525cd)
![image](https://github.com/ecotaxa/ecotaxa_front/assets/90832786/4a6dd375-31a7-4b05-bee6-1c194984c98f)
![image](https://github.com/ecotaxa/ecotaxa_front/assets/90832786/f8916893-babb-4b31-bb61-7cbbbdba4996)

**Comment by grololo06** [comment]
It's a Google Recaptcha issue which appears under "some conditions":
https://stackoverflow.com/questions/53497287/google-recaptcha-v3-error-timeout-or-duplicate

https://github.com/google/recaptcha/issues/302

**Comment by grololo06** [comment]
To reproduce: open a private navigation window, go to https://ecotaxa.obs-vlfr.fr/register, fill in the form and wait (I just did 5 minutes) before submitting:
![image](https://github.com/ecotaxa/ecotaxa_front/assets/20199778/9d20d307-0bdb-47b7-b586-80bc288f1466)
