### ISSUE TITLE
Increase available number of metadata for process, acquisition and sample

### ISSUE THREAD

**Issue by juliecoust** [ecotaxa/ecotaxa_front#855]
We would like to have : 
- acq up to 50
- process up to 50 
- sample up to 100

It should be changed [here](https://github.com/ecotaxa/ecotaxa_back/blob/ad457255d2ceda53536ef25ab1ccc09612416400/py/DB/Sample.py#L14).

The UI should take that into account dans reflect these changes.

QA tests should be adapted.

**Comment by grololo06** [comment]
On hold.

**Comment by grololo06** [comment]
@bea777515 we can close maybe?

**Comment by juliecoust** [comment]
La limite a été augmentée ?

**Comment by bea777515** [comment]
oui , on est passé à 60
je vais fermer l'issue

Le lun. 9 oct. 2023 à 11:03, Julie Coustenoble ***@***.***> a
écrit :
