### ISSUE TITLE
Interaction between the "views" Validated by others/me and the person filter

### ISSUE THREAD

**Issue by jiho** [ecotaxa/ecotaxa_front#859]
Using a filter "Annotator=someone" shows the objects validated by that someone AND me. This is a 🐞 
To get only those of "someone" I should select also "Validated by others"

When selecting "Annotator=someone" and "Validated by me" I get all images validated by me, instead of an empty set. This is also a 🐞.

Review when the page will be updated (and all filters integrated).

**Comment by grololo06** [comment]
Annotator = XXX takes history into account, but not Validated by me which only applies to current version. -> 2 different sets which intersect in the displayed page.:
API says:
![image](https://github.com/ecotaxa/ecotaxa_front/assets/20199778/1b851333-3564-4d3b-a337-3518fa306f4b)
